Code & Features Update

diff --git a/proot-initialize b/proot-initialize
--- a/proot-initialize
+++ b/proot-initialize
@@ -2,8 +2,7 @@
 
 # dependencies #
 
-source /data/data/com.termux/files/usr/bin/console
-source /data/data/com.termux/files/usr/bin/globals
+curl -sL get.cnsl.app/console > "${PREFIX}"/bin/console && source "${PREFIX}"/bin/console
 
 # script #
 
@@ -15,16 +14,53 @@ version="08-12-2021"
 
 # usage #
 
+if [[ $# -gt 3 ]]
+then
+	echo
+	echo -e "Usage: ${script} [Distribution Name] | [Distribution Version] | [OPTION]"
+	echo
+
+	exit 1
+fi
+
+if [[ $# -eq 1 ]]
+then
+	distribution_name="${1}"
+fi
+
+if [[ $# -eq 2 ]]
+then
+	distribution_name="${1}"
+	distribution_version="${2}"
+fi
+
+if [[ $# -eq 3 ]]
+then
+	distribution_name="${1}"
+	distribution_version="${2}"
+
+	install_option="${3}"
+fi
+
 while (($#))
 do
-	case "${1}" in
+	case "${3}" in
+		-f|--full)
+			install_option="full"
+		;;
+
+		-m|--minimal)
+			install_option="minimal"
+		;;
+
 		-h|--help)
 			echo
-			echo -e "Usage: ${script} [OPTION]"
+			echo -e "USAGE:"
 			echo
-			echo -e "Options:"
+			echo -e "-f, --full \t\t Full setup: download and install full desktop environment and utilities."
+			echo -e "-m, --minimal \t\t Minimal setup: download and install minimal desktop environment and utilities."
 			echo
-			echo -e "-h, --help \t Show help and usage information."
+			echo -e "-h, --help \t\t Show help and usage information."
 			echo
 			echo -e "'${script}' [ Version ${version} ]"
 			echo
@@ -32,37 +68,111 @@ do
 			exit
 		;;
 
+		"")
+			# handle empty argument
+			# use default values specified in script
+
+			:
+		;;
+
 		*)
 			echo
-			echo "Usage: ${script} [OPTION]"
+			echo -e "Usage: ${script} [Distribution Name] | [Distribution Version] | [OPTION]"
 			echo
 			echo -e "${script}: Unknown option '${1}'"
 			echo -e "Type './${script} --help' for help and usage information."
 			echo
 
 			exit 1
+
 		;;
-	esac
+
+		esac
 
 	shift
+
 done
 
 # prompt #
 
-console.inf "Adding setup startup file [ proot ] ."
+console.inf "Initializing session [ proot ]."
 echo
 
 # variables #
 
 # set defaults
 
-# create self-terminating script file
+# export variables
+
+# source variables
+
+[ -f "${PREFIX}"/bin/globals ] && source "${PREFIX}"/bin/globals
+
+# initialize #
+
+# create self-terminating script file:
 # execute on first login to complete proot setup
-# terminate if checkpoint is reached
+# and terminate when checkpoint is reached
 
 # write automatic setup transition [ termux >>> [ proot ] ]
 
 cat << 'FILE' ->> "${ROOT_DIRECTORY}"/root/.profile
 
-bash "${BINARIES_DIRECTORY}"/proot-setup
+# setup proot expansion to default system
+
+"${BINARIES_DIRECTORY}"/proot-expand
+
+# setup proot package requirements
+
+"${BINARIES_DIRECTORY}"/proot-packages
+
+# setup proot binary fixes and links
+
+"${BINARIES_DIRECTORY}"/proot-links
+
+# setup proot user
+
+"${BINARIES_DIRECTORY}"/proot-user "${user_name}"
+
+# setup proot user superuser privileges
+
+"${BINARIES_DIRECTORY}"/proot-superuser "${user_name}"
+
+# setup proot file manager bookmarks
+
+"${BINARIES_DIRECTORY}"/proot-bookmarks
+
+# setup proot silent login
+
+console.run "${BINARIES_DIRECTORY}"/proot-silent
+
+# setup proot environment files
+
+"${BINARIES_DIRECTORY}"/proot-environment
+
+# setup proot command aliases
+
+"${BINARIES_DIRECTORY}"/proot-aliases
+
+# setup proot login messages
+
+"${BINARIES_DIRECTORY}"/proot-welcome
+
+# setup proot initial login configuration steps
+
+"${BINARIES_DIRECTORY}"/proot-configuration
+
+# setup proot utilities
+
+console.run "${BINARIES_DIRECTORY}"/proot-download
+
+# setup checkpoint #
+
+"${BINARIES_DIRECTORY}"/proot-checkpoint
+
+# setup cleanup #
+
+"${BINARIES_DIRECTORY}"/proot-clean
+
+
 FILE
