Code & Features Update

diff --git a/termux-shell b/termux-shell
--- a/termux-shell
+++ b/termux-shell
@@ -93,6 +93,12 @@ FILE
 
 cat << 'FILE' -> "${HOME}"/.bashrc
 
+# check for interactive session
+
+[ -z "$PS1" ] && return
+
+# set shell options
+
 shopt -s checkwinsize
 shopt -s histappend
 shopt -s histverify
@@ -101,7 +107,9 @@ HISTCONTROL=ignoreboth
 HISTSIZE=1000
 HISTFILESIZE=2000
 
-if ! shopt -oq posix
+# bash completion
+
+if [ ! $(shopt -oq posix) ]
 then
 	if [ -f /usr/share/bash-completion/bash_completion ]
 	then
@@ -113,7 +121,33 @@ then
 	fi
 fi
 
-# dextop #
+# command not found
+
+if [ -x /usr/lib/command-not-found ] || [ -x /usr/share/command-not-found/command-not-found ]
+then
+	command_not_found_handle () {
+		if [ -x /usr/lib/command-not-found ]
+		then
+			/usr/lib/command-not-found -- "${1}"
+
+			return $?
+
+		elif [ -x /usr/share/command-not-found/command-not-found ]
+		then
+			/usr/share/command-not-found/command-not-found -- "${1}"
+
+			return $?
+		else
+			printf "%s: command not found\n" "${1}" >&2
+
+			return 127
+		fi
+	}
+fi
+
+# prompt string
+
+# ansi colors escape setup using 'tput'
 
 black="\001$(tput setaf 0)\002"
 red="\001$(tput setaf 1)\002"
@@ -130,23 +164,19 @@ reset="\001$(tput sgr 0)\002"
 
 unset PS1
 
-if [[ $(id -u) = 0 ]]
-then
-	PS1+="${reset}[ "
-	PS1+="${red}${USER}"
-	PS1+="${reset} ]"
-	PS1+="${white} >_ # ${reset}"
-else
-	PS1+="${reset}[ "
-	PS1+="${green}${USER}"
-	PS1+="${reset} ]"
-	PS1+="${white} >_ $ ${reset}"
-fi
+[[ $(id -u) = 0 ]] && PS1+="${reset}[ "				|| PS1+="${reset}[ "
+[[ $(id -u) = 0 ]] && PS1+="${red}${USER}"			|| PS1+="${green}${USER}"
+[[ $(id -u) = 0 ]] && PS1+="${reset} ]"				|| PS1+="${reset} ]"
+[[ $(id -u) = 0 ]] && PS1+="${white} >_ # ${reset}"	|| PS1+="${white} >_ $ ${reset}"
+
+# bash aliases
 
 if [ -f "${HOME}"/.bash_aliases ]
 then
 	. "${HOME}"/.bash_aliases
 fi
+
+# bash functions
 
 if [ -f "${HOME}"/.bash_functions ]
 then
